### ISSUE TITLE
Failed to load the atom-live-server-plus package

### ISSUE THREAD

**Issue by MiltonCobo** [richiksc/atom-live-server-plus#3] opened 2018-11-03 15:20 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-live-server-plus](https://github.com/richiksc/atom-live-server-plus) package 2.4.1

### Stack Trace

Failed to load the atom-live-server-plus package

```
At Unexpected token { in JSON at position 373

SyntaxError: Unexpected token { in JSON at position 373
    at JSON.parse (<anonymous>)
    at m (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:576223)
    at c (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:576518)
    at Object.readFileSync (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:577611)
    at keymaps.getKeymapPaths.map.e (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:3036837)
    at Array.map (<anonymous>)
    at Package.loadKeymaps (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:3036825)
    at measure (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:3030379)
    at Package.measure (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:3029574)
    at Package.load (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:3030315)
    at PackageManager.loadAvailablePackage (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:378592)
    at config.transact (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:377015)
    at Config.transact (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:329551)
    at PackageManager.loadPackages (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:11:376953)
    at t.loadState.then (~/AppData/Local/atom/app-1.32.1/resources/app/static/<embedded>:1:642340)
    at <anonymous>
```

### Commands

```
     -0:22.8.0 core:backspace (input.hidden-input)
     -0:21.6.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
atom-auto-prettier 0.1.1 
atom-auto-resize 0.5.1 
atom-autocomplete-php 0.25.6 
atom-html-preview 0.2.5 
atom-live-server 2.3.0 
atom-live-server-plus 2.4.1 
emmet 2.4.3 
file-icons 2.1.26 
```

**Comment by richiksc** [comment] 2018-11-03 20:29
@MiltonCobo Thank you for the report. One major thing that stands out to me is you have both `atom-live-server` and `atom-live-server-plus` installed. You're not supposed to have both `atom-live-server` and `atom-live-server-plus` installed at the same time, as `atom-live-server-plus` is a replacement for `atom-live-server`. Please uninstall atom-live-server and see if the issue persists.

**Comment by richiksc** [comment] 2019-03-04 19:35
Closing this issue as I have not received updates in a while and am unable to reproduce the bug.

**Closed by richiksc** 2019-03-04 19:35 UTC
