### ISSUE TITLE
Uncaught ReferenceError: stopServer is not defined

### ISSUE THREAD

**Issue by akibrahim2001** [richiksc/atom-live-server-plus#1] opened 2018-09-26 14:17 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Microsoft Windows 10 Home
**Thrown From**: [atom-live-server-plus](https://github.com/richiksc/atom-live-server-plus) package 2.4.1

### Stack Trace

Uncaught ReferenceError: stopServer is not defined

```
At C:\Users\InternetUser\.atom\packages\atom-live-server-plus\lib\atom-live-server.js:139

ReferenceError: stopServer is not defined
    at Object.startServer (/packages/atom-live-server-plus/lib/atom-live-server.js:139:7)
    at HTMLElement.atomLiveServerStartServer (/packages/atom-live-server-plus/lib/atom-live-server.js:66:50)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.30.0/resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (~/AppData/Local/atom/app-1.30.0/resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchApplicationMenuCommand (~/AppData/Local/atom/app-1.30.0/resources/app/src/atom-environment.js:1351:25)
    at EventEmitter.outerCallback (~/AppData/Local/atom/app-1.30.0/resources/app/src/application-delegate.js:339:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -0:37.5.0 atom-live-server:startServer (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-live-server 2.3.0 
atom-live-server-plus 2.4.1 
livestyle-atom 0.2.10 
php-server 0.8.0 
```

**Comment by richiksc** [comment] 2018-09-26 15:04
@akibrahim2001 Try uninstalling atom-live-server. atom-live-server-plus is supposed to replace atom-live-server, not supplement it. Also, could I get some steps to reproduce the exception? Did you just call `:stopServer`?

**Comment by richiksc** [comment] 2019-03-04 19:34
Try updating your package to `v3.0.0`. Closing this issue as I was unable to reproduce and was not responded to with more info.

**Closed** 2019-03-04 19:34 UTC
